GET http://localhost:8081/products/

###

GET http://localhost:8081/products/64a017302991751855bbb2cb


###


GET http://localhost:8081/products/category/football


###



GET http://localhost:8081/products/groupproductsbycat/football


###




GET http://localhost:8081/products/groupproductsbybrand/adidas


###


GET http://localhost:8081/products/brand/adidas


###



GET http://localhost:8081/products/price/50/100



###


POST http://localhost:8081/products/
Content-Type: application/json
//full POST - works

{
    "name":"Messi's Shoes",
    "category":"football",
    "brand": "adidas",
    "description": "good for grass and kicking",
    "amountInInventory": 6,
    "video": "https://www.youtube.com/watch?v=hvmURkVDZyI",
    "image": "https://m.media-amazon.com/images/I/71gFzfxnGIS._AC_UL600_FMwebp_QL65_.jpg",
    "price": 100
}


###


POST http://localhost:8081/products/
Content-Type: application/json
//partial POST - works

{
    "name":"partial POST test",
    "category":"football shoes"

}


###


PUT http://localhost:8081/products/649fc35bcb38b032dd949f8a
Content-Type: application/json
//Accept: application/json
//Full PUT - works

{
    "name": "new name for search",
    "image": "image test",
    "video": "video test",
    "brand": "brand test",
    "category": "category test",
    "description": "description test",
    "amountInInventory": 25,
}

###

PUT http://localhost:8081/products/64a017302991751855bbb2cb
Content-Type: application/json
//Accept: application/json
//Partial PUT - works

{
    "price": 99
}




###

DELETE  http://localhost:8081/products/64a00b4c71050196fcfe61c3


