GET http://localhost:80/products/

###

GET http://localhost:80/products/64a017302991751855bbb2cb


###


GET http://localhost:80/products/category/football


###



GET http://localhost:80/products/groupproductsbycat/football


###




GET http://localhost:80/products/groupproductsbybrand/adidas


###


GET http://localhost:80/products/brand/adidas


###



GET http://localhost:80/products/price/50/100



###


POST http://localhost:80/products/
Content-Type: application/json
//full POST - works

{
    "name": "Coleman",
    "category":"Running",
    "brand": "Adidas",
    "description": "Good for very long distance",
    "amountInInventory": 3,
    "video": "https://www.youtube.com/embed/T2PHutsuBdw",
    "image": "https://imagescdn.reebok.in/img/app/product/7/772037-8886887.jpg?auto=format",
    "price": 220
}


###


POST http://localhost:80/products/
Content-Type: application/json
//partial POST - works

{
    "name":"partial POST test",
    "category":"football shoes"

}


###


GET http://localhost:80/products/category/football
Content-Type: application/json
//category GET


###


PUT http://localhost:80/products/64b0fc8aa6010202cd0ecfa0
Content-Type: application/json
//Accept: application/json


{
    "name" : "Ronaldo"
}

###

PUT http://localhost:80/products/64a017302991751855bbb2cb
Content-Type: application/json
//Accept: application/json
//Partial PUT - works

{
    "amount": 99
}




###

DELETE  http://localhost:80/products/64a00b4c71050196fcfe61c3


