GET http://localhost:80/users/

###

GET http://localhost:80/users/64b11618ed57dfe58471e4c0

###


GET http://localhost:80/users/username/user

###


GET http://localhost:80/


###


POST http://localhost:80/users/
Content-Type: application/json
//full POST - works

{
    "username" : "Amit2",
    "password":"12345",
    "deliveryAdress": "Allenby 300",
    "userType":"Regular"
}


###


POST http://localhost:80/users/
Content-Type: application/json
//partial POST - works

{
    "name":"BB nice shoes"
}


###


PUT http://localhost:80/users/64b11618ed57dfe58471e4c0
Content-Type: application/json
//Accept: application/json
//Full PUT - works

{
    "username":"Ytal"
}

###

//TODO change user product list

PUT http://localhost:80/users/64a01d791e54b4812186ace7
Content-Type: application/json
//Accept: application/json
//Partial PUT - works

{
    "deliveryAdress": "Allenby 100"
}




###

DELETE  http://localhost:80/users/64b23951191d3cd964abbcf2


