GET http://localhost:80/users/

###

GET http://localhost:80/users/64a943893a06f7af153dab7f

###


GET http://localhost:80/users/username/user

###


GET http://localhost:80/


###


POST http://localhost:80/users/
Content-Type: application/json
//full POST - works

{
    "username" : "Amit",
    "password":"12345",
    "deliveryAdress": "Allenby 300",
    "userType":"Regular",
    "shoppoigCart": ""
}


###


POST http://localhost:80/users/
Content-Type: application/json
//partial POST - works

{
    "name":"BB nice shoes"

}


###


PUT http://localhost:80/users/64a01d791e54b4812186ace7
Content-Type: application/json
//Accept: application/json
//Full PUT - works

{
    "username":"usertestnumber2 new name",
    "password":"1234567890newpass",
    "userType":"regular",
    "deliveryAdress": "Allenby 200"
}

###

//TODO change user product list

PUT http://localhost:80/users/64a01d791e54b4812186ace7
Content-Type: application/json
//Accept: application/json
//Partial PUT - works

{
    "deliveryAdress": "Allenby 100"
}




###

DELETE  http://localhost:80/users/64a01d461e54b4812186ace0


