
//CTOR of product 
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const Product = new Schema({
    //ID is generated by Mongo Automatically
    name: {
        type: String,
        required: [true, "name is required"],
    },
    image: {
        type: String,
        required: [true, "image is required"],
    },
    video: {
        type: String,
    },
    brand: {
        type: String,
        enum: ['Adidas', 'Nike', 'Reebok'],
        required: [true, "category is required"],
    },
    description: {
        type: String,
    },
    category: {
        type: String,
        enum: ['Football', 'Basketball', 'Running'],
        required: [true, "category is required"],
    },
    amountInInventory: {
        type: Number,
        min: 1,
        max: 100,
    }, 
    price: {
        type: Number,
        required: [true, "price is required"],
        min: 1,
        max: 1000,
    }
});

//exporting it to controler 
module.exports = mongoose.model('product',Product)