
//CTOR of product 
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const Product = new Schema({
    //ID is generated by Mongo Automatically
    name: {
        type: String,
    },
    image: {
        type: String,
    },
    video: {
        type: String,
    },
    brand: {
        type: String,
    },
    description: {
        type: String,
    },
    category: {
        type: String,
    },
    amountInInventory: {
        type: Number,
   },
    price: {
        type: Number,
    }
});

//exporting it to controler 
module.exports = mongoose.model('product',Product)