 
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const Product = require('../models/product')


const purchaseHistory = new Schema({
    //ID is generated by Mongo Automatically
    uderID: {
        type: String,
    },
    productList: [
        {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'Product'
        }
    ]
    }
    );

module.exports = mongoose.model('purchasehistory',purchaseHistory)