 
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const Product = require('../models/product')



const Supplier = new Schema({
    //ID is generated by Mongo Automatically
    name: {
        type: String,
    },
    productList: [
        {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'Product'
        }
    ],
    email: {
        type: String,
    }
});

//exporting it to controler 
module.exports = mongoose.model('supplier',Supplier)