 
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const User = new Schema({
    //ID is generated by Mongo Automatically
    username: {
        type: String,
        required: [true, "username is required, please re-enter"],
    },
    password: {
        type: String,
        required: [true, "password is required, please re-enter"],
    },
    //TODO make reference to shopping cart objects
    shoppingCart: {
        type: String,
    },
    deliveryAdress: {
        type: String,
    },
    userType: {
        type: String,
        enum: ['Admin', 'Regular'],
        required: [true, "type is required, please re-enter"],
    },
});

//exporting it to controler 
module.exports = mongoose.model('user',User)