 
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const User = new Schema({
    //ID is generated by Mongo Automatically
    username: {
        type: String,
    },
    password: {
        type: String,
    },
    //TODO make reference to shopping cart object
    shoppingCart: {
        type: String,
    },
    deliveryAdress: {
        type: String,
    },
    userType: {
        type: String,
    },
});

//exporting it to controler 
module.exports = mongoose.model('user',User)